// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SerializedClient
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Serialized API
    /// </summary>
    public partial interface ISerialized : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Store events
        /// </summary>
        /// <remarks>
        /// Stores all events in the request atomically. All events must refer
        /// to the same aggregate id.
        /// </remarks>
        /// <param name='aggregateType'>
        /// The aggregate type.
        /// </param>
        /// <param name='aggregateId'>
        /// The unique id of the aggregate
        /// </param>
        /// <param name='eventBatch'>
        /// Batch of one or more events
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> StoreEventsWithHttpMessagesAsync(string aggregateType, System.Guid aggregateId, EventBatch eventBatch, string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Bulk Store events
        /// </summary>
        /// <remarks>
        /// Bulk stores all events in the request atomically. All events must
        /// refer to unique aggregate ids.
        /// </remarks>
        /// <param name='aggregateType'>
        /// The aggregate type.
        /// </param>
        /// <param name='bulk'>
        /// Bulk of one or more batches
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> BulkStoreEventsWithHttpMessagesAsync(string aggregateType, Bulk bulk, string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete all aggregates by type
        /// </summary>
        /// <remarks>
        /// Permanently delete all aggregates, including all events, for given
        /// aggregate type.
        /// </remarks>
        /// <param name='aggregateType'>
        /// The aggregate type
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='deleteToken'>
        /// Valid delete token. Will be included in the response of the first
        /// DELETE request.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<DeleteAggregatesByTypeOKResponse>> DeleteAggregatesByTypeWithHttpMessagesAsync(string aggregateType, string serializedTenantId = default(string), System.Guid? deleteToken = default(System.Guid?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List aggregates by type
        /// </summary>
        /// <remarks>
        /// List aggregates to get the current version and last updated time.
        /// </remarks>
        /// <param name='aggregateType'>
        /// The aggregate type
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='skip'>
        /// Optional number to start from
        /// </param>
        /// <param name='limit'>
        /// Optional limit. Default is 1000.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ListAggregatesByTypeOKResponse>> ListAggregatesByTypeWithHttpMessagesAsync(string aggregateType, string serializedTenantId = default(string), int? skip = default(int?), int? limit = default(int?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Check if an aggregate exists
        /// </summary>
        /// <param name='aggregateType'>
        /// The aggregate type
        /// </param>
        /// <param name='aggregateId'>
        /// The unique id of the aggregate
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> AggregateExistsWithHttpMessagesAsync(string aggregateType, System.Guid aggregateId, string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete an aggregate
        /// </summary>
        /// <remarks>
        /// Permanently delete an aggregate, including all events.
        /// </remarks>
        /// <param name='aggregateType'>
        /// The aggregate type
        /// </param>
        /// <param name='aggregateId'>
        /// The unique id of the aggregate
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='deleteToken'>
        /// Valid delete token. Will be included in the response to the first
        /// DELETE request.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<DeleteAggregateOKResponse>> DeleteAggregateWithHttpMessagesAsync(string aggregateType, System.Guid aggregateId, string serializedTenantId = default(string), System.Guid? deleteToken = default(System.Guid?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Load all events for an aggregate
        /// </summary>
        /// <remarks>
        /// By loading all events for a single aggregate we can derive the
        /// current state.
        /// </remarks>
        /// <param name='aggregateType'>
        /// The aggregate type
        /// </param>
        /// <param name='aggregateId'>
        /// The unique id of the aggregate
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='since'>
        /// Optional version number to start from
        /// </param>
        /// <param name='limit'>
        /// Optional version limit. Default is 1000.
        /// </param>
        /// <param name='includeMetadata'>
        /// Adds timestamp and aggregateVersion to the response.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<LoadEventsOKResponse>> LoadEventsWithHttpMessagesAsync(string aggregateType, System.Guid aggregateId, string serializedTenantId = default(string), int? since = default(int?), int? limit = default(int?), bool? includeMetadata = false, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get event feeds overview
        /// </summary>
        /// <remarks>
        /// Overview showing number of batches, aggregates and events per
        /// aggregate type.
        /// </remarks>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ListFeedsOKResponse>> ListFeedsWithHttpMessagesAsync(string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get current global sequence number
        /// </summary>
        /// <remarks>
        /// Get current global sequence number at head for all feeds
        /// </remarks>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationHeaderResponse<GetCurrentGlobalSequenceNumberHeaders>> GetCurrentGlobalSequenceNumberWithHttpMessagesAsync(string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get feed of events for all types
        /// </summary>
        /// <remarks>
        /// Get all events for all aggregates for all types (feed names). The
        /// payload is returned with the event batches in insertion order, each
        /// with a unique sequence number.
        /// </remarks>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='since'>
        /// Optional sequence number to start from (exclusive)
        /// </param>
        /// <param name='limit'>
        /// Optional response limit. Default is 1000.
        /// </param>
        /// <param name='fromParameter'>
        /// Optional ISO 8601 date-time string to start from, inclusive, eg.
        /// 2017-07-21T17:32:28.
        /// </param>
        /// <param name='to'>
        /// Optional ISO 8601 date-time string to stop at, exclusive, eg.
        /// 2017-07-21T17:32:28.
        /// </param>
        /// <param name='partitionCount'>
        /// The expected total number of partitions, i.e. the total number of
        /// consumers feeding in parallel.
        /// </param>
        /// <param name='partitionNumber'>
        /// The partition number to request.
        /// </param>
        /// <param name='waitTime'>
        /// If provided, will generate a long-polling request. This is the
        /// maximum time (in ms) to wait before responding. Maximum value is
        /// 60000.
        /// </param>
        /// <param name='filterType'>
        /// If provided, filters the feed on the given aggregate types. Provide
        /// multiple values to filter on more than one aggregate type.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Feed>> FeedEventsWithHttpMessagesAsync(string serializedTenantId = default(string), int? since = default(int?), int? limit = 1000, System.DateTime? fromParameter = default(System.DateTime?), System.DateTime? to = default(System.DateTime?), int? partitionCount = 1, int? partitionNumber = 0, int? waitTime = 0, IList<string> filterType = default(IList<string>), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get total number of event batches
        /// </summary>
        /// <remarks>
        /// Get the total number of event batches.
        /// </remarks>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='fromParameter'>
        /// Optional ISO 8601 date-time string to start from, inclusive, eg.
        /// 2017-07-21T17:32:28.
        /// </param>
        /// <param name='to'>
        /// Optional ISO 8601 date-time string to stop at, exclusive,
        /// 2017-07-21T17:32:28.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<GetCountOKResponse>> GetCountWithHttpMessagesAsync(string serializedTenantId = default(string), System.DateTime? fromParameter = default(System.DateTime?), System.DateTime? to = default(System.DateTime?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get current sequence number
        /// </summary>
        /// <remarks>
        /// Get current sequence number at head for a given feed
        /// </remarks>
        /// <param name='name'>
        /// The name of the feed
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationHeaderResponse<GetCurrentSequenceNumberHeaders>> GetCurrentSequenceNumberWithHttpMessagesAsync(string name, string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get feed of events
        /// </summary>
        /// <remarks>
        /// Get all events for all aggregates given a type (feed name). The
        /// payload is returned with the event batches in insertion order, each
        /// with a unique sequence number.
        /// </remarks>
        /// <param name='name'>
        /// The name of the feed (aggregate type)
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='since'>
        /// Optional sequence number to start from, exclusive.
        /// </param>
        /// <param name='limit'>
        /// Optional response limit. Default is 1000.
        /// </param>
        /// <param name='fromParameter'>
        /// Optional ISO 8601 date-time string to start from, inclusive, eg.
        /// 2017-07-21T17:32:28.
        /// </param>
        /// <param name='to'>
        /// Optional ISO 8601 date-time string to stop at, exclusive,
        /// 2017-07-21T17:32:28.
        /// </param>
        /// <param name='partitionCount'>
        /// The expected total number of partitions, i.e. the total number of
        /// consumers feeding in parallel.
        /// </param>
        /// <param name='partitionNumber'>
        /// The partition number to request.
        /// </param>
        /// <param name='waitTime'>
        /// If provided, will generate a long-polling request. This is the
        /// maximum time (in ms) to wait before responding. Maximum value is
        /// 60000.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Feed>> FeedEventsByTypeWithHttpMessagesAsync(string name, string serializedTenantId = default(string), int? since = default(int?), int? limit = 1000, System.DateTime? fromParameter = default(System.DateTime?), System.DateTime? to = default(System.DateTime?), int? partitionCount = 1, int? partitionNumber = 0, int? waitTime = 0, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get total number of event batches
        /// </summary>
        /// <remarks>
        /// Get the number of event batches for a given aggregate type (feed
        /// name).
        /// </remarks>
        /// <param name='name'>
        /// The name of the feed (aggregate type)
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='fromParameter'>
        /// Optional ISO 8601 date-time string to start from, inclusive, eg.
        /// 2017-07-21T17:32:28.
        /// </param>
        /// <param name='to'>
        /// Optional ISO 8601 date-time string to stop at, exclusive,
        /// 2017-07-21T17:32:28.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<GetCountByTypeOKResponse>> GetCountByTypeWithHttpMessagesAsync(string name, string serializedTenantId = default(string), System.DateTime? fromParameter = default(System.DateTime?), System.DateTime? to = default(System.DateTime?), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List reactions
        /// </summary>
        /// <remarks>
        /// List reactions
        /// </remarks>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='status'>
        /// Status to filter. Possible values are: SCHEDULED, READY, ONGOING,
        /// COMPLETED, CANCELED, FAILED.
        /// </param>
        /// <param name='skip'>
        /// Number of entries to skip
        /// </param>
        /// <param name='limit'>
        /// Max number of entries to include in response. Default is 10.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Reactions>> ListReactionsWithHttpMessagesAsync(string serializedTenantId = default(string), string status = "ALL", int? skip = 0, int? limit = 10, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete a scheduled reaction
        /// </summary>
        /// <remarks>
        /// This endpoint allows you to delete a reaction that has not yet been
        /// executed.
        /// </remarks>
        /// <param name='reactionId'>
        /// ID of the scheduled reaction to delete.
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> DeleteScheduledReactionWithHttpMessagesAsync(System.Guid reactionId, string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Execute a scheduled or completed reaction
        /// </summary>
        /// <remarks>
        /// This endpoint allows you to execute a scheduled or completed
        /// reaction.
        /// </remarks>
        /// <param name='reactionId'>
        /// ID of the reaction to execute.
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ExecuteReactionWithHttpMessagesAsync(System.Guid reactionId, string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List reaction definitions
        /// </summary>
        /// <remarks>
        /// List all reaction definitions
        /// </remarks>
        /// <param name='skip'>
        /// Number of entries to skip
        /// </param>
        /// <param name='limit'>
        /// Max number of entries to include in response. Default is 100.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ReactionDefinitions>> ListReactionDefinitionsWithHttpMessagesAsync(int? skip = 0, int? limit = 100, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create reaction definition
        /// </summary>
        /// <remarks>
        /// Create a new reaction definition
        /// </remarks>
        /// <param name='reactionDefinition'>
        /// The reaction definition
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> CreateReactionDefinitionWithHttpMessagesAsync(ReactionDefinition reactionDefinition, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete a reaction definition
        /// </summary>
        /// <param name='reactionName'>
        /// The reaction name
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> DeleteReactionDefinitionWithHttpMessagesAsync(string reactionName, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get reaction definition
        /// </summary>
        /// <param name='reactionName'>
        /// The reaction name
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ReactionDefinition>> GetReactionDefinitionWithHttpMessagesAsync(string reactionName, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update reaction definition
        /// </summary>
        /// <param name='reactionName'>
        /// The reaction name
        /// </param>
        /// <param name='reactionDefinition'>
        /// The reaction definition
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> CreateOrUpdateReactionDefinitionWithHttpMessagesAsync(string reactionName, ReactionDefinition reactionDefinition, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get projections overview
        /// </summary>
        /// <remarks>
        /// Includes projection names and count
        /// </remarks>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ListProjectionsOKResponse>> ListProjectionsWithHttpMessagesAsync(string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List projection definitions
        /// </summary>
        /// <remarks>
        /// List all definitions
        /// </remarks>
        /// <param name='skip'>
        /// Number of entries to skip
        /// </param>
        /// <param name='limit'>
        /// Max number of entries to include in response. Default is 100.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ProjectionDefinitions>> ListProjectionDefinitionsWithHttpMessagesAsync(int? skip = 0, int? limit = 100, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Create a projection definition
        /// </summary>
        /// <remarks>
        /// Create a new definition
        /// </remarks>
        /// <param name='projectionDefinition'>
        /// Definition of the projection
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> CreateProjectionDefinitionWithHttpMessagesAsync(ProjectionDefinition projectionDefinition, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get projection definition
        /// </summary>
        /// <param name='projectionName'>
        /// The projection name
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ProjectionDefinition>> GetProjectionDefinitionWithHttpMessagesAsync(string projectionName, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update a projection definition
        /// </summary>
        /// <remarks>
        /// Create or update a definition
        /// </remarks>
        /// <param name='projectionName'>
        /// The projection name
        /// </param>
        /// <param name='projectionDefinition'>
        /// Definition of the projection
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> CreateOrUpdateProjectionDefinitionWithHttpMessagesAsync(string projectionName, ProjectionDefinition projectionDefinition, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete projection definition
        /// </summary>
        /// <param name='projectionName'>
        /// The projection name
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> DeleteProjectionDefinitionWithHttpMessagesAsync(string projectionName, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List single projections
        /// </summary>
        /// <remarks>
        /// List all single projections
        /// </remarks>
        /// <param name='projectionName'>
        /// The projection name
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='reference'>
        /// Reference string to filter on. See JsonPath 'setref' for details.
        /// </param>
        /// <param name='fromParameter'>
        /// Filter reference value from. Usable if reference is a date or
        /// timestamp.
        /// </param>
        /// <param name='to'>
        /// Filter reference value to. Usable if reference is a date or
        /// timestamp.
        /// </param>
        /// <param name='search'>
        /// String to search for. The projection has to be created with
        /// 'indexedFields'.
        /// </param>
        /// <param name='sort'>
        /// Sort string. Any combination of the following fields: projectionId,
        /// reference, createdAt, updatedAt. Add '+' and '-' prefixes to
        /// indicate ascending/descending sort order. Ascending order is
        /// default.
        /// </param>
        /// <param name='skip'>
        /// Number of entries to skip
        /// </param>
        /// <param name='limit'>
        /// Max number of entries to include in response. Default is 100.
        /// </param>
        /// <param name='id'>
        /// If provided, filters on the projection id(s) to only get the
        /// specified projections. Provide multiple values to retrieve multiple
        /// projections in the response.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Projections>> ListSingleProjectionsWithHttpMessagesAsync(string projectionName, string serializedTenantId = default(string), string reference = default(string), string fromParameter = default(string), string to = default(string), string search = default(string), string sort = default(string), int? skip = 0, int? limit = 100, IList<string> id = default(IList<string>), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete/recreate single projections
        /// </summary>
        /// <remarks>
        /// This call deletes all existing projections and starts a rebuild
        /// from the beginning of the event history. Keep in mind that this
        /// might take a while.
        /// </remarks>
        /// <param name='projectionName'>
        /// The projection name
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> RecreateSingleProjectionsWithHttpMessagesAsync(string projectionName, string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get single projection count
        /// </summary>
        /// <param name='projectionName'>
        /// The projection name
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='reference'>
        /// Optional reference string to filter on.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ProjectionCount>> GetSingleProjectionCountWithHttpMessagesAsync(string projectionName, string serializedTenantId = default(string), string reference = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get single projection
        /// </summary>
        /// <param name='projectionName'>
        /// The projection name
        /// </param>
        /// <param name='projectionId'>
        /// The projectionId
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='awaitCreation'>
        /// Max number of milliseconds to await the initial creation. Must be
        /// between 1 and 60000.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Projection>> GetSingleProjectionWithHttpMessagesAsync(string projectionName, System.Guid projectionId, string serializedTenantId = default(string), int? awaitCreation = 0, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get aggregated projection
        /// </summary>
        /// <param name='projectionName'>
        /// The projection name
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Projection>> GetAggregatedProjectionWithHttpMessagesAsync(string projectionName, string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete/recreate aggregated projections
        /// </summary>
        /// <remarks>
        /// This call deletes all existing projections and starts a rebuild
        /// from the beginning of the event history. Keep in mind that this
        /// might take a while.
        /// </remarks>
        /// <param name='projectionName'>
        /// The projection name
        /// </param>
        /// <param name='serializedTenantId'>
        /// The optional ID of the tenant.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> RecreateAggregatedProjectionsWithHttpMessagesAsync(string projectionName, string serializedTenantId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// List tenants
        /// </summary>
        /// <remarks>
        /// List tenants
        /// </remarks>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Tenants>> ListTenantsWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Add tenant
        /// </summary>
        /// <remarks>
        /// Add tenant
        /// </remarks>
        /// <param name='tenant'>
        /// Tenant
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> AddTenantWithHttpMessagesAsync(Tenant tenant, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update tenant
        /// </summary>
        /// <remarks>
        /// Update tenant
        /// </remarks>
        /// <param name='tenantId'>
        /// The tenant id
        /// </param>
        /// <param name='tenant'>
        /// Tenant
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> UpdateTenantWithHttpMessagesAsync(string tenantId, Tenant tenant, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Delete tenant
        /// </summary>
        /// <remarks>
        /// Delete tenant
        /// </remarks>
        /// <param name='tenantId'>
        /// The tenant id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> DeleteTenantWithHttpMessagesAsync(System.Guid tenantId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Undelete tenant
        /// </summary>
        /// <remarks>
        /// Undelete tenant
        /// </remarks>
        /// <param name='tenantId'>
        /// The tenant id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> UndeleteTenantWithHttpMessagesAsync(string tenantId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
