// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SerializedClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Bulk
    {
        /// <summary>
        /// Initializes a new instance of the Bulk class.
        /// </summary>
        public Bulk()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Bulk class.
        /// </summary>
        public Bulk(IList<EventBatch> events = default(IList<EventBatch>))
        {
            Events = events;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "events")]
        public IList<EventBatch> Events { get; set; }

    }
}
