// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SerializedClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetCountOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetCountOKResponse class.
        /// </summary>
        public GetCountOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetCountOKResponse class.
        /// </summary>
        /// <param name="totalCount">Total count</param>
        public GetCountOKResponse(long? totalCount = default(long?))
        {
            TotalCount = totalCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets total count
        /// </summary>
        [JsonProperty(PropertyName = "totalCount")]
        public long? TotalCount { get; set; }

    }
}
