// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SerializedClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ListProjectionsOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the ListProjectionsOKResponse class.
        /// </summary>
        public ListProjectionsOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ListProjectionsOKResponse class.
        /// </summary>
        public ListProjectionsOKResponse(IList<ProjectionInfo> projections = default(IList<ProjectionInfo>))
        {
            Projections = projections;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projections")]
        public IList<ProjectionInfo> Projections { get; set; }

    }
}
