// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SerializedClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The list of aggregates.
    /// </summary>
    public partial class ListAggregatesByTypeOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the ListAggregatesByTypeOKResponse
        /// class.
        /// </summary>
        public ListAggregatesByTypeOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ListAggregatesByTypeOKResponse
        /// class.
        /// </summary>
        /// <param name="hasMore">Indicates if there are more summaries
        /// available.</param>
        public ListAggregatesByTypeOKResponse(IList<AggregateSummary> aggregates = default(IList<AggregateSummary>), bool? hasMore = default(bool?))
        {
            Aggregates = aggregates;
            HasMore = hasMore;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aggregates")]
        public IList<AggregateSummary> Aggregates { get; set; }

        /// <summary>
        /// Gets or sets indicates if there are more summaries available.
        /// </summary>
        [JsonProperty(PropertyName = "hasMore")]
        public bool? HasMore { get; set; }

    }
}
