// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SerializedClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The aggregate containing all its events, since the beginning of time.
    /// </summary>
    public partial class LoadEventsOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the LoadEventsOKResponse class.
        /// </summary>
        public LoadEventsOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LoadEventsOKResponse class.
        /// </summary>
        /// <param name="aggregateVersion">Current aggregate version. Can be
        /// passed as 'expectedVersion' on next update to enable optimistic
        /// concurrency control.</param>
        /// <param name="hasMore">Indicates if there are more versions
        /// available.</param>
        public LoadEventsOKResponse(System.Guid? aggregateId = default(System.Guid?), int? aggregateVersion = default(int?), string aggregateType = default(string), IList<EventModel> events = default(IList<EventModel>), bool? hasMore = default(bool?))
        {
            AggregateId = aggregateId;
            AggregateVersion = aggregateVersion;
            AggregateType = aggregateType;
            Events = events;
            HasMore = hasMore;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aggregateId")]
        public System.Guid? AggregateId { get; set; }

        /// <summary>
        /// Gets or sets current aggregate version. Can be passed as
        /// 'expectedVersion' on next update to enable optimistic concurrency
        /// control.
        /// </summary>
        [JsonProperty(PropertyName = "aggregateVersion")]
        public int? AggregateVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aggregateType")]
        public string AggregateType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "events")]
        public IList<EventModel> Events { get; set; }

        /// <summary>
        /// Gets or sets indicates if there are more versions available.
        /// </summary>
        [JsonProperty(PropertyName = "hasMore")]
        public bool? HasMore { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (AggregateType != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(AggregateType, "^[a-z0-9]+[a-z0-9\\-_]+[a-z0-9]+$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "AggregateType", "^[a-z0-9]+[a-z0-9\\-_]+[a-z0-9]+$");
                }
            }
            if (Events != null)
            {
                foreach (var element in Events)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
