// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SerializedClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProjectionDefinitions
    {
        /// <summary>
        /// Initializes a new instance of the ProjectionDefinitions class.
        /// </summary>
        public ProjectionDefinitions()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProjectionDefinitions class.
        /// </summary>
        /// <param name="hasMore">Indicates if there are more definitions
        /// available.</param>
        public ProjectionDefinitions(IList<ProjectionDefinition> definitions, bool? hasMore = default(bool?), int? totalCount = default(int?))
        {
            Definitions = definitions;
            HasMore = hasMore;
            TotalCount = totalCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "definitions")]
        public IList<ProjectionDefinition> Definitions { get; set; }

        /// <summary>
        /// Gets or sets indicates if there are more definitions available.
        /// </summary>
        [JsonProperty(PropertyName = "hasMore")]
        public bool? HasMore { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalCount")]
        public int? TotalCount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Definitions == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Definitions");
            }
            if (Definitions != null)
            {
                foreach (var element in Definitions)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
