// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SerializedClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Projections
    {
        /// <summary>
        /// Initializes a new instance of the Projections class.
        /// </summary>
        public Projections()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Projections class.
        /// </summary>
        /// <param name="hasMore">Indicates if there are more projections
        /// available.</param>
        public Projections(IList<Projection> projectionsProperty, int totalCount, bool? hasMore = default(bool?))
        {
            ProjectionsProperty = projectionsProperty;
            HasMore = hasMore;
            TotalCount = totalCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projections")]
        public IList<Projection> ProjectionsProperty { get; set; }

        /// <summary>
        /// Gets or sets indicates if there are more projections available.
        /// </summary>
        [JsonProperty(PropertyName = "hasMore")]
        public bool? HasMore { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalCount")]
        public int TotalCount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ProjectionsProperty == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ProjectionsProperty");
            }
            if (ProjectionsProperty != null)
            {
                foreach (var element in ProjectionsProperty)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
