// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SerializedClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProjectionCount
    {
        /// <summary>
        /// Initializes a new instance of the ProjectionCount class.
        /// </summary>
        public ProjectionCount()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProjectionCount class.
        /// </summary>
        /// <param name="count">The projection count</param>
        public ProjectionCount(long? count = default(long?))
        {
            Count = count;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the projection count
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public long? Count { get; set; }

    }
}
