// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SerializedClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Tenant
    {
        /// <summary>
        /// Initializes a new instance of the Tenant class.
        /// </summary>
        public Tenant()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Tenant class.
        /// </summary>
        /// <param name="tenantNumber">The ever increasing tenent
        /// number.</param>
        /// <param name="addedAt">Tenant added timestamp</param>
        /// <param name="reference">Optional external tenant reference, e.g. a
        /// customer number or similar.</param>
        /// <param name="deleted">Indicates if the tenant was deleted.</param>
        public Tenant(System.Guid tenantId, string tenantNumber = default(string), long? addedAt = default(long?), string reference = default(string), bool? deleted = default(bool?))
        {
            TenantId = tenantId;
            TenantNumber = tenantNumber;
            AddedAt = addedAt;
            Reference = reference;
            Deleted = deleted;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tenantId")]
        public System.Guid TenantId { get; set; }

        /// <summary>
        /// Gets or sets the ever increasing tenent number.
        /// </summary>
        [JsonProperty(PropertyName = "tenantNumber")]
        public string TenantNumber { get; set; }

        /// <summary>
        /// Gets or sets tenant added timestamp
        /// </summary>
        [JsonProperty(PropertyName = "addedAt")]
        public long? AddedAt { get; set; }

        /// <summary>
        /// Gets or sets optional external tenant reference, e.g. a customer
        /// number or similar.
        /// </summary>
        [JsonProperty(PropertyName = "reference")]
        public string Reference { get; set; }

        /// <summary>
        /// Gets or sets indicates if the tenant was deleted.
        /// </summary>
        [JsonProperty(PropertyName = "deleted")]
        public bool? Deleted { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
