name: Build & Test
on: [ push ]
jobs:
  client-dotnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Run scenario test
      env:
        SERIALIZED_ACCESS_KEY: ${{ secrets.SERIALIZED_DOTNET_TEST_ACCESS_KEY }}
        SERIALIZED_SECRET_ACCESS_KEY: ${{ secrets.SERIALIZED_DOTNET_TEST_SECRET_ACCESS_KEY }}
      run: dotnet test SerializedClientTest
